# Generated by Django 5.2.3 on 2025-06-13 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
